# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  displayName: 'Use .NET 6 Core sdk'
  inputs:
    packageType: 'sdk'
    version: '6.0.x'
    includePreviewVersions: true

- script: dotnet build --configuration $(buildConfiguration)  eShopOnWeb.sln
  displayName: 'dotnet build $(buildConfiguration) eShopOnWeb.sln' 

- task: DotNetCoreCLI@2
  inputs:
      command: 'test'
      projects: 'test/Unit Tests/*.csprog'
      testRunTitle: 'unit test'
      arguments: '--configuration $(buildConfiguration)' # Update this to match your need


- task: DotNetCoreCLI@2
  inputs:
      command: 'test'
      projects: 'test/IntegrationTests/*.csprog'
      testRunTitle: 'Integration test'